version: "1"
rules:
  - base: master
    upstream: cloudbox:master
    mergeMethod: hardreset
  - base: develop
    upstream: cloudbox:develop
    mergeMethod: hardreset
  - base: develop_python3
    upstream: cloudbox:develop_python3
    mergeMethod: hardreset
