---
version: 1.0.0-{build}

skip_tags: true

skip_commits:
  files:

    # Git
    - '.gitignore'
    - '.gitmodules'
    - '.github/**/*'

    # Docs
    - '*.md'

    # Vagrant
    - 'Vagrantfile'

    # Ansible Misc
#    - 'defaults/**/*'
#    - 'roles/*/files/**/*'
#    - 'filter_plugins/**/*'
#    - 'inventories/**/*'
#    - 'library/**/*'

    # Ansible Roles - Core
#    - 'roles/settings/**/*'
#    - 'roles/backup/**/*'
#    - 'roles/restore/**/*'

    # Ansible Roles - Extras
    - 'roles/cloudflare/**/*'
    - 'roles/ddclient/**/*'
    - 'roles/feeder/**/*'
    - 'roles/mariadb/**/*'
    - 'roles/nginx/**/*'
    - 'roles/notify/**/*'
    - 'roles/nvidia/**/*'
    - 'roles/nzbthrottle/**/*'
    - 'roles/plex_auth_token/**/*'
    - 'roles/plex_dupefinder/**/*'
    - 'roles/plex_patrol/**/*'
    - 'roles/python-plexlibrary/**/*'
    - 'roles/sickbeard_mp4_automator/**/*'
    - 'roles/sstvirl/**/*'
    - 'roles/subliminal/**/*'
    - 'roles/trackarr/**/*'
    - 'roles/traktarr/**/*'

  message: /\[minor\]/

build_cloud: CLOUDBOX

image: 
  - Ubuntu1804
  - Ubuntu2004

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: curl -s https://raw.githubusercontent.com/Cloudbox/cb/develop_python3/cb_dep.sh | sudo -H bash
  - sh: sudo mkdir /srv/git
  - sh: sudo ln -s /home/appveyor/projects/cloudbox /srv/git/cloudbox
  - sh: sudo chown -R appveyor:appveyor /srv/git

install:
  - sh: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done
  - sh: curl -o daemon.json https://raw.githubusercontent.com/saltydk/AppveyorTest/main/daemon.json
  - sh: cp -f daemon.json /home/appveyor/projects/cloudbox/roles/docker/templates/daemon.json.j2
  - sh: sudo ansible-playbook cloudbox.yml --syntax-check
  - sh: |
      sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" \
          --skip-tags "settings" \
          --extra-vars '{"continuous_integration":true}'
