########################################################################################
# Title:         Cloudbox: Settings | Migrator | 'ansible.cfg' | Migration 01          #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/cloudbox/cloudbox                                  #
# --                                                                                   #
#                 Part of the Cloudbox project: https://cloudbox.works                 #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################
---
- name: "Migrator | 'ansible.cfg' | Add default entries to 'ansible.cfg'"
  ini_file:
    path: "{{ playbook_dir }}/{{ file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    no_extra_spaces: no
    owner: "{{ cloudbox_yml.stat.uid }}"
    group: "{{ cloudbox_yml.stat.gid }}"
    mode: 0664
  register: ansible_cfg_update_status
  loop:
    - { section: 'defaults', option: 'inventory', value: './inventories/local' }
    - { section: 'defaults', option: 'roles_path', value: 'roles:resources/roles' }
    - { section: 'defaults', option: 'fact_path', value: './ansible_facts.d' }
    - { section: 'defaults', option: 'log_path', value: './cloudbox.log' }
    - { section: 'defaults', option: 'callback_whitelist', value: 'profile_tasks' }
    - { section: 'defaults', option: 'command_warnings', value: False }
    - { section: 'defaults', option: 'retry_files_enabled', value: False }
    - { section: 'defaults', option: 'hash_behaviour', state: 'absent' }
    - { section: 'defaults', option: 'interpreter_python', value: '/usr/bin/python3' }

- name: "Migrator | 'ansible.cfg' | Remove deprecated hash_behaviour entry"
  shell: |
    sed -i '/hash_behaviour/d' /srv/git/cloudbox/ansible.cfg
  become: yes
  become_user: "{{ cloudbox_yml.stat.pw_name }}"

- name: "Migrator | 'ansible.cfg' | Build 'files_updated_successfully' list"
  set_fact:
    files_updated_successfully: "{{ files_updated_successfully }} + [ '{{ file }}' ]"
    exit_is_necessary: true
  when: item.changed
  loop: "{{ ansible_cfg_update_status.results }}"
